### ISSUE TITLE
Настройка ключевого слова удалённо. 

### ISSUE THREAD

**Issue by lanket** [devoff/mdmPiTerminal#2]
Получение через сокеты от модуля majordomo команды record:
 Далее идет набор управляющих кодов
- start,1
Старт записи первого файла образца ключевого слова 
- stop,3
Стоп записи третьего файла образца ключевого слова 
- play,2
Воспроизвезти файл записи второго образца ключевого слова 
- compile
Скомпилить файл ключевого слова для сноубоя

**Comment by devoff** [comment]
Можно добавить возможность прослушать запись для проверки

**Comment by lanket** [comment]
Ну так play для этого и придумал. Чел нажал кнопку в модуле мажора прослушать к примеру 3й файл. По сокету прилетает record:play3 и терминал воспроизводит 3й файл

**Comment by dance12r** [comment]
Не работает, скорее всего из-за того, что через модуль передается комманда "rec0_1" (mpt_edit.html), а на стороне Апельсина ждем "rec1_1"(sayreply.py)

**Comment by dance12r** [comment]
так же с play и compile

**Comment by dance12r** [comment]
fixed
