### ISSUE TITLE
Передача настроек из модуля Мажордомо 

### ISSUE THREAD

**Issue by lanket** [devoff/mdmPiTerminal#3]
Во первых настройки надо выне ти в отдельный файл. 
Команда settings:
Содержит json с настройками для терминала

- sensitivity=0.4
Чувствительность на ключевое слово 
- alarmkwactivated=1
ДиньДон после реакции на ключевое слово 
- alarmtts=1
ДиньДон перед произношением команд tts и ask
- alarmstt=1
ДиньДон перед  запуском записи файла для распознования 
- providertts=
Варианты параметров:
- - google
- - yandex
- - ... 
- apikeytts=ApiKeyForTtsProvider
- providerstt:
Варианты параметров:
- - google
- - yandex
- - wit
- - ... 
- apikeytts=ApiKeyForSttProvider

**Comment by devoff** [comment]
так же включение светодиодов и выбор GPIO для них

**Comment by lanket** [comment]
Хорошая идея. Но мне всеже больше прильщает мысть WS2812B

**Comment by dance12r** [comment]
https://github.com/lanket/mdmPiTerminalModule/issues/2
Есть некоторое несоответствие переменных передаваемы через модуль и тех которых ожидает snowboy.py

**Comment by dance12r** [comment]
fixed in last pull request
